### ISSUE TITLE
Using cocaine-framework-python in Windows environment

### ISSUE THREAD

**Issue by bombastic1** [cocaine/cocaine-framework-python#36]
Hello,
Could you please advise a proper way to use cocaine-framework-python in Windows environment.
I would like to connect to mastermind from windows but results to this traceback in cocaine:

>>> import mastermind
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\mastermind\__init__.py", line 1, in <module>
    from mastermind.client import MastermindClient
  File "C:\Python27\lib\mastermind\client.py", line 4, in <module>
    from mastermind.service import ReconnectableService
  File "C:\Python27\lib\mastermind\service.py", line 6, in <module>
    from cocaine.logging import Logger
  File "C:\Python27\lib\cocaine\logging\__init__.py", line 1, in <module>
    from cocaine.logging.logger import Logger
  File "C:\Python27\lib\cocaine\logging\logger.py", line 25, in <module>
    from cocaine.asio.service import Service
  File "C:\Python27\lib\cocaine\asio\service.py", line 11, in <module>
    from cocaine.asio.pipe import Pipe
  File "C:\Python27\lib\cocaine\asio\pipe.py", line 6, in <module>
    import fcntl
ImportError: No module named fcntl

I am using cocaine-framework-python-0.11 branch.
Then I've found a dummy module
https://communities.cisco.com/servlet/JiveServlet/download/150596-65641/fcntl.py.zip
which returns always zero for that function:

def fcntl(fd, op, arg=0):
    return 0

and inserted it to python's Lib folder.
But it isn't solved the problem, because apparently the fcntl is module that can only be used in linux os. What should I do?

**Comment by noxiouz** [comment]
Done
